# Generated by Django 4.2.2 on 2023-10-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playarchive", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Achive", new_name="Archive",),
    ]
