# Generated by Django 4.2.2 on 2023-10-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playarchive", "0002_rename_achive_archive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "アーカイブ", "verbose_name_plural": "アーカイブ"},
        ),
    ]
