# Generated by Django 4.2.2 on 2023-10-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playarchive", "0003_alter_movie_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="achive", new_name="archive",
        ),
    ]
