# Generated by Django 4.2.2 on 2023-10-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playarchive", "0004_rename_achive_movie_archive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie", options={"verbose_name": "動画", "verbose_name_plural": "動画"},
        ),
    ]
