# Generated by Django 4.2.2 on 2023-10-16 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playarchive", "0006_alter_archive_archiveid"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="archive",),
        migrations.AddField(
            model_name="movie",
            name="archiveid",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivenumber",
                to="playarchive.archive",
            ),
            preserve_default=False,
        ),
    ]
