# Generated by Django 4.2.2 on 2023-10-24 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playarchive", "0008_remove_movie_archiveid_movie_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="archive",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="playarchive.archive",
            ),
        ),
    ]
